### ISSUE TITLE
Pinned giveaways aren't filtered by ESGST with theme enabled

### ISSUE THREAD

**Issue by montoner0** [SquishedPotatoe/SGv2-Dark#1]
**Description**
Pinned giveaways (upper part of the giveaways list) aren't filtered if a dark theme is enabled. Noticed this after ESGST dropped themes support and suddenly these giveaways are gone.

**Steps to Reproduce**

1. Go to https://www.steamgifts.com/
2. Configure filters to hide some games from pinned list
3. Enable SGv2 Dark theme
4. Pinned giveaways reappeared

**Expected Behavior**
Giveaways are still hidden.

**Console Errors**
No errors

**Screenshots**
![image](https://user-images.githubusercontent.com/13542804/92311432-996beb00-efbf-11ea-86d6-3871b9ebd405.png)
![image](https://user-images.githubusercontent.com/13542804/92311421-835e2a80-efbf-11ea-99d4-774f485bff61.png)

**System (please complete the following information):**

- ESGST Version: Extension v8.8.1
- Browser + Version: Firefox v80.0.1
- SGv2 Dark version: v1.6.2

**Comment by SquishedPotatoe** [comment]
Fixed in https://github.com/SquishedPotatoe/SGv2-Dark/commit/fbaae6db507feb960d8fd6470e510e24a68505a5
