### ISSUE TITLE
Avatars are misaligned in discussions block on main page with ESGST

### ISSUE THREAD

**Issue by montoner0** [SquishedPotatoe/SGv2-Dark#2]
**Description**
For discussions with long title (with ellipsis at end) the avatars are misaligned.

**Screenshots**
![image](https://user-images.githubusercontent.com/13542804/92323881-daf2a980-f044-11ea-873a-9a2231289b71.png)
![image](https://user-images.githubusercontent.com/13542804/92323871-c57d7f80-f044-11ea-8c88-f64a15e6bcd9.png)

**System**
- ESGST Version: Extension v8.8.1
- Browser + Version: Firefox v80.0.1
- SGv2 Dark: v1.6.2

**Comment by SquishedPotatoe** [comment]
fixed in https://github.com/SquishedPotatoe/SGv2-Dark/commit/b103e34e8993985c72b1cf0edc27b00b15b7cb74
